name: Auto Set PR

on:
  pull_request:
    types: [ready_for_review]  # 設定為可審查

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add Label to PR
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.base.ref;
            let label = branch.startsWith("develop") ? "develop" : "feature";

            github.rest.issues.addLabels({
              labels: [label]
            });
